fix Otp error
Zummit-Africa-Inc/zapi-lambda-identity pull request #29
Opened 2022-09-23 12:08 UTC by johnayinde

- added core service url to env.example file: to communicate with the core service in creating a user profile after a successful email verification
- fix invalid OTP: throw error for an invalid OTP

2022-09-23 12:27 UTC, SunmadeBabafemi approved these changes

2022-09-24 19:27 UTC, Chimexx requested changes
Fix your conflicts

2022-09-24 19:27 UTC, Chimexx commented on .env.example
> +CORE_SERVICE_URL=http://localhost:3001/api/v1
Any need for this? My Your port may not be the same with mine.

2022-09-24 19:27 UTC, Chimexx commented on src/email-verification/email-verification.controller.ts
> -    return ZaLaResponse.Ok<object>({user} , 'Profile created', 201);
This is what we have now

![image](https://user-images.githubusercontent.com/84224449/192115049-97fd6e5a-978e-47d7-bf90-596471ca2c72.png)

2022-09-25 19:59 UTC, closed without merging